name: ai-merge

on:
  pull_request:
    types: [closed]

env: 
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENDPOINT: ${{ secrets.ENDPOINT}}
  GENMINI_API_TOKEN: ${{ secrets.GENMINI_API_TOKEN }}

jobs:
  ai-merge:
    permissions:
      read-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd .github/scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd ../..

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd .github/scripts
          npm install

      - name: Sent summary
        run: |
          python .github/scripts/api.py "$GH_TOKEN" ${{ github.repository }} ${{ github.event.pull_request.number }} "$ENDPOINT" "$GENMINI_API_TOKEN"