name: send on merge

on:
    pull_request:
        types: [closed]

jobs:
    send-on-merge:
        permissions:
            read-all
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - uses: 8BitJonny/gh-get-current-pr@3.0.0
              id: PR
              with:
                sha: ${{ github.event.pull_request.head.sha }}
            - env: 
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo "https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.PR.outputs.number }}/comments"

                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/pulls/${{ steps.PR.outputs.number }}/comments