name: health check

on:
    workflow_dispatch:

env: 
    ENDPOINT: ${{ secrets.ENDPOINT }}

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - run: |
                curl "$ENDPOINT/ping"